// Generated by CoffeeScript 1.10.0
(function() {
  var coffeeGlob;

  coffeeGlob = ['src/**/*.', './*.'];

  module.exports = {
    coffeeSrc: coffeeGlob.map(function(glob) {
      return glob + 'coffee';
    }),
    litcoffeeSrc: coffeeGlob.map(function(glob) {
      return glob + 'litcoffee';
    }),
    coffeeDst: 'build'
  };

}).call(this);
