// Generated by CoffeeScript 1.10.0
(function() {
  var config, genCoffeeTask, gulp, gulpChanged, gulpCoffee, gulpCoffeeLint, gulpUtil;

  gulp = require('gulp');

  gulpCoffee = require('gulp-coffee');

  gulpCoffeeLint = require('gulp-coffeelint');

  gulpUtil = require('gulp-util');

  gulpChanged = require('gulp-changed');

  config = require('./config');

  gulp.task('coffee-watch', function() {
    gulp.watch(config.coffeeSrc, ['coffee']);
    return gulp.watch(config.litcoffeeSrc, ['litcoffee']);
  });

  genCoffeeTask = function(literate) {
    return function() {
      var task;
      task = gulp.src(config.coffeeSrc).pipe(gulpChanged(config.coffeeDst));
      if (gulpUtil.env.type === 'dev') {
        task.pipe(gulpCoffeeLint()).pipe(gulpCoffeeLint.reporter('coffeelint-stylish')).pipe(gulpCoffeeLint.reporter('fail'));
      }
      return task.pipe(gulpCoffee({
        bare: true,
        literate: literate
      }).on('error', gulpUtil.log)).pipe(gulp.dest(config.coffeeDst));
    };
  };

  gulp.task('coffee', genCoffeeTask(false));

  gulp.task('litcoffee', genCoffeeTask(true));

}).call(this);
